name: Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and create tag
        id: tag
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M%S')" # timestamp-based tag
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $VERSION
          git push origin $VERSION

      - name: Checkout build repo
        uses: actions/checkout@v4
        with:
          repository: karthik-narayan-v/RecipeApp-Build
          token: ${{ secrets.GITHUB_TOKEN }}
          path: build-repo

      - name: Trigger build workflow
        run: |
          gh workflow run build.yml -R karthik-narayan-v/RecipeApp-Build -f version=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
